-- 创建数据库
CREATE DATABASE IF NOT EXISTS `node_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 使用该数据库
USE `node_db`;

-- 用户表
CREATE TABLE `Users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `password` VARCHAR(100) NOT NULL,
  `role` ENUM('admin', 'user') DEFAULT 'user',
  `token` TEXT,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Cloth 商品表
CREATE TABLE `Cloths` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `type` VARCHAR(100) NOT NULL,
  `size` VARCHAR(10) DEFAULT 'M',
  `color` VARCHAR(20),
  `material` VARCHAR(50),
  `price` FLOAT NOT NULL,
  `isDeleted` BOOLEAN DEFAULT FALSE,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 投资组合表
CREATE TABLE `Portfolios` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `userId` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `isDeleted` BOOLEAN DEFAULT FALSE,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`userId`) REFERENCES `Users`(`id`) ON DELETE CASCADE
);

-- 公共资产信息表
CREATE TABLE `Assets` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `assetCode` VARCHAR(20) NOT NULL UNIQUE,
  `name` VARCHAR(100) NOT NULL,
  `assetType` ENUM('stock', 'bond', 'cash') NOT NULL,
  `price` DECIMAL(15,4) NOT NULL DEFAULT 0,
  `currency` VARCHAR(10) DEFAULT 'USD',
  `historyPriceArr` JSON,
  `dateArr` JSON,
  `isDeleted` BOOLEAN DEFAULT FALSE,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 投资资产表
CREATE TABLE `PortfolioItems` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `portfolioId` INT NOT NULL,
  `assetCode` VARCHAR(20) NOT NULL,
  `assetType` ENUM('stock', 'bond', 'cash') NOT NULL,
  `amount` DECIMAL(15,4) NOT NULL,
  `quantity` DECIMAL(15,4) NOT NULL,
  `type` ENUM('buy', 'sell') NOT NULL,
  `sellDate` DATE,
  `purchaseDate` DATE NOT NULL,
  `isDeleted` BOOLEAN DEFAULT FALSE,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`portfolioId`) REFERENCES `Portfolios`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`assetCode`) REFERENCES `Assets`(`assetCode`) ON DELETE RESTRICT
);

-- 收益记录表
CREATE TABLE `ProfitLogs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `itemId` INT NOT NULL,
  `date` DATE NOT NULL,
  `value` DECIMAL(15,4) NOT NULL,
  `profit` DECIMAL(15,4) NOT NULL,
  `isDeleted` BOOLEAN DEFAULT FALSE,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`itemId`) REFERENCES `PortfolioItems`(`id`) ON DELETE CASCADE
);
